# Generated by Django 4.2.7 on 2023-12-05 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicsite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
    ]
